apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka
  template:
    metadata:
      labels:
        app: java-kafka
    spec:
      hostNetwork: true
      containers:
        - name: java-app
          image: fabandalm/java-kafka-client:1.0.0
          ports:
            - containerPort: 8080
        - name: kafka-sidecar
          image: fabandalm/kafka-sidecar-python:1.0.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-sidecar-service
spec:
  selector:
    app: java-kafka  # This matches the label of the pods created by the deployment
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000